INPUT:
  FORMAT: "RGB"
  MIN_SIZE_TRAIN: (512, )
  MAX_SIZE_TRAIN: 640
  MIN_SIZE_TRAIN_SAMPLING: "choice"
  MIN_SIZE_TEST: 512
  MAX_SIZE_TEST: 640
OUTPUT_DIR: "./output"
DATASETS:
  TRAIN: ("voc_2007_trainval", "voc_2012_trainval")
  TEST: ("voc_2007_test",)
MODEL:
  META_ARCHITECTURE: "RetinaNet"
  BACKBONE:
    NAME: "build_retinanet_efficientnet_bifpn_backbone"
  EFFICIENTNET:
    OUT_FEATURES: ["res4", "res7", "res10", "res14", "res15"]
  BIFPN:
    IN_FEATURES: ["res4", "res7", "res10", "res14", "res15"]
  RETINANET:
    NUM_CLASSES: 20
    IN_FEATURES: ["p3", "p4", "p5", "p6", "p7"]
    NUM_CONVS: 1
SOLVER:
  IMS_PER_BATCH: 2
  BASE_LR: 0.01
  STEPS: (15000, 25000)
  MAX_ITER: 100  # 17.4 epochs
  WARMUP_ITERS: 100
  EMA:
    DECAY: 0.9998
    PERIOD: 2
VERSION: 2
