INPUT:
  FORMAT: "RGB"
OUTPUT_DIR: ""
DATALOADER:
  ASPECT_RATIO_GROUPING: false
MODEL:
  META_ARCHITECTURE: EfficientNet
SOLVER:
  IMS_PER_BATCH: 384
  BASE_LR: 0.1
  STEPS: (20000, 60000, )
  MAX_ITER: 100000
VERSION: 2
