_BASE_: "./base.yaml"
MODEL:
  DEVICE: "cuda:0"
  META_ARCHITECTURE: "RetinaNet"
  BACKBONE:
    NAME: "build_retinanet_shufflenetv2_fpn_backbone"
  RETINANET:
    IOU_THRESHOLDS: [0.4, 0.5]
    IOU_LABELS: [0, -1, 1]
  FPN:
    IN_FEATURES: ["stage2", "stage3", "stage4"]
    OUT_CHANNELS: 256
    NORM: ""
    FUSE_TYPE: "sum"
  SHUFFLENETV2:
    RATIO: 0.5
    IMAGENET_PRETRAINED_MODEL: /home/lijun/.cache/torch/checkpoints/shufflenetv2_x0.5-f707e7126e.pth
  ANCHOR_GENERATOR:
    SIZES: !!python/object/apply:eval ["[[x, x * 2**(1.0/3), x * 2**(2.0/3) ] for x in [32, 64, 128, 256, 512 ]]"]
VERSION: 2
