DATASETS:
  TRAIN: ("voc_2007_trainval", "voc_2012_trainval")
  TEST: ("voc_2007_test",)
INPUT:
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800)
  MIN_SIZE_TEST: 800
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.01
  STEPS: (12000, 16000)
  MAX_ITER: 18000
  WARMUP_ITERS: 100
VIS_PERIOD:
  10
