_BASE_: "./base.yaml"
MODEL:
  META_ARCHITECTURE: "RetinaNet"
  BACKBONE:
    NAME: "build_retinanet_shufflenetv2_fpn_backbone"
  RETINANET:
    IOU_THRESHOLDS: [0.4, 0.5]
    IOU_LABELS: [0, -1, 1]
    NUM_CLASSES: 20
  FPN:
    IN_FEATURES: ["stage2", "stage3", "stage4"]
    OUT_CHANNELS: 256
    NORM: ""
    FUSE_TYPE: "sum"
  SHUFFLENETV2:
    RATIO: 0.5
    IMAGENET_PRETRAINED_MODEL: /home/lijun/.cache/torch/checkpoints/shufflenetv2_x0.5-f707e7126e.pth
  ANCHOR_GENERATOR:
    SIZES: [[32, 40, 50], [64, 80, 100], [128, 160, 200], [256, 320, 400], [512, 645, 812]]
    ASPECT_RATIOS: [[0.5, 1.0, 2.0]]
VERSION: 2
