_BASE_: "Base-RetinaNet.yaml"
MODEL:
  WEIGHTS: ""
  MOBILENETV3:
    OUT_FEATURES: ["res2", "res8", "res12"]
    PRETRAINED_MODEL_PATH: "G:\\pre_trained_models\\MobileNetv3\\mbv3_small.pth.tar"
  FPN:
    IN_FEATURES: ["res2", "res8", "res12"]
